ARG IMAGE=alpine:3.15
FROM ${IMAGE}

RUN apk add --no-cache sudo git

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

RUN adduser -u ${USER_UID} -g ${USER_GID} -D ${USERNAME} && \
    echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

RUN apk add --no-cache cmake ninja g++ libxft-dev libxcursor-dev
